### ISSUE TITLE
Remove #[feature(unicode)] to allow this crate to compile on stable

### ISSUE THREAD

**Issue by laumann** [pzol/xml_writer#5]
Hi! I wanted to use the [xlsx](https://docs.rs/crate/xlsx/0.1.0) crate, which depends on this crate. But this crate doesn't compile on stable. I tried cloning this crate and removing `#[feature(unicode)]` and that seems to be all there is to it.

Should I make a PR?

**Comment by pzol** [comment]
Sure, please do


Piotr
